name: CI

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout V UI
      uses: actions/checkout@v2
      with:
        path: vlib/ui
    - name: Install dependencies
      run: |
        sudo rm -f /etc/apt/sources.list.d/dotnetdev.list /etc/apt/sources.list.d/microsoft-prod.list
        sudo apt-get update
        sudo apt-get install --quiet -y libglfw3 libglfw3-dev libfreetype6-dev libgtk-3-dev
    - name: Build V
      run: |
        make
        sudo ./v symlink
    - name: Build UI examples
      run: |
        cd ./vlib/ui/examples/
        v run ./build_examples.vsh

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout V UI
      uses: actions/checkout@v2
      with:
        path: vlib/ui
    - name: Install dependencies
      run: |
        brew install freetype glfw
    - name: Build V
      run: |
        make
        ./v symlink
    - name: Build UI examples
      run: |
        cd ./vlib/ui/examples/
        v run ./build_examples.vsh

  windows-msvc:
    runs-on: windows-latest
    env:
        VFLAGS: -cc msvc
    steps:
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout V UI
      uses: actions/checkout@v2
      with:
        path: vlib/ui
    - name: Checkout dependencies
      uses: actions/checkout@v2
      with:
        path: thirdparty/freetype
        repository: ubawurinna/freetype-windows-binaries
    - name: Build V
      run: |
        .\make.bat
    # Don't move applying V directory to PATH, to other steps
    # otherwise this step and V script won't see V executable.
    - name: Build UI examples
      run: |
        $env:path += ";$(get-location)"
        cd .\vlib\ui\examples\
        & v run .\build_examples.vsh
