name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '31 1,12 * * *'

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  linux:
    uses: ./.github/workflows/linux.yml

  macos:
    uses: ./.github/workflows/macos.yml

  windows:
    uses: ./.github/workflows/windows.yml
