name: CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '31 1,12 * * *'

jobs:
  code-formatting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout V UI
      uses: actions/checkout@v2
      with:
        path: vlib/ui
    - name: Build V
      run: make
    - name: v fmt -verify
      run: ./v fmt -verify vlib/ui

  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout V UI
      uses: actions/checkout@v2
      with:
        path: vlib/ui
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --quiet -y libglfw3-dev libxi-dev libxcursor-dev
    - name: Build V
      run: |
        make
        sudo ./v symlink
    - name: Build UI examples
      run: |
        cd ./vlib/ui/examples/
        v run ./build_examples.vsh
        echo 'Build users.v with -prod'
        v -prod users.v

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout V UI
      uses: actions/checkout@v2
      with:
        path: vlib/ui
    - name: Build V
      run: |
        make
        ./v symlink
    - name: Build UI examples
      run: |
        cd ./vlib/ui/examples/
        v run ./build_examples.vsh
        echo 'Build users.v with -prod'
        v -prod users.v
        v users.v

  windows-msvc:
    runs-on: windows-latest
    env:
        VFLAGS: -cc msvc
    steps:
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout V UI
      uses: actions/checkout@v2
      with:
        path: vlib/ui
    - name: Build V
      run: |
        .\make.bat -msvc
    # Don't move applying V directory to PATH, to other steps
    # otherwise this step and V script won't see V executable.
    - name: Build UI examples
      run: |
        $env:path += ";$(get-location)"
        cd .\vlib\ui\examples\
        & v run .\build_examples.vsh
        echo 'Build users.v with -prod'
        v -prod users.v
        echo "=========================="
        echo "v -showcc .\users.v"
